name: Govulncheck
on:
  schedule:
    - cron: "0 */6 * * *" # Run every 6 hours
jobs:
  govulncheck:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
          cache: true
      - name: Install Govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Run Govulncheck
        run: govulncheck ./...
